import { Router } from 'express';
import authRoutes from './auth.routes';
import ticketRoutes from './ticket.routes';
import commentRoutes from './comment.routes';
import attachmentRoutes from './attachment.routes';
import dashboardRoutes from './dashboard.routes';
import userRoutes from './user.routes';
import notificationRoutes from './notification.routes';
import itemMasterRoutes from './itemMaster.routes';
import planRoutes from './plan.routes';
import customerRoutes from './customer.routes';
import supplierRoutes from './supplier.routes';
import employeeRoutes from './employee.routes';
import scheduleRoutes from './schedule.routes';
import groupRoutes from './group.routes';
import workshopRoutes from './workshop.routes';
import productionlineRoutes from './productionline.routes';
import materiaPropertyRoutes from './materiaProperty.routes';
import materialClassRoutes from './materialClass.routes';
import productClassRoutes from './productClass.routes';
import equipmentRoutes from './equipment.routes';
import mouldRoutes from './mould.routes';
import taskRoutes from './task.routes';
import procedureRoutes from './procedure.routes';
import workCenterRoutes from './workCenter.routes';
import routingRoutes from './routing.routes';
import warehouseRoutes from './warehouse.routes';
import routingMasterRoutes from './routingMaster.routes';
import approvalRoutes from './approval.routes';
import bomRoutes from './bom.routes';
import unitRoutes from './unit.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/tickets', ticketRoutes);
router.use('/', commentRoutes);
router.use('/', attachmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', userRoutes);
router.use('/notifications', notificationRoutes);
router.use('/item-masters', itemMasterRoutes);
router.use('/plans', planRoutes);
router.use('/customers', customerRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/employees', employeeRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/groups', groupRoutes);
router.use('/workshops', workshopRoutes);
router.use('/productionlines', productionlineRoutes);
router.use('/materia-properties', materiaPropertyRoutes);
router.use('/material-classes', materialClassRoutes);
router.use('/product-classes', productClassRoutes);
router.use('/equipments', equipmentRoutes);
router.use('/moulds', mouldRoutes);
router.use('/tasks', taskRoutes);
router.use('/procedures', procedureRoutes);
router.use('/work-centers', workCenterRoutes);
router.use('/routings', routingRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/routing-masters', routingMasterRoutes);
router.use('/approval', approvalRoutes);
router.use('/boms', bomRoutes);
router.use('/units', unitRoutes);

export default router;
