import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware';
import multer from 'multer';
import { getProcedures, createProcedure, updateProcedure, deleteProcedure, exportProcedures, importProcedures } from '../controllers/procedure.controller';
const router = Router();
const upload = multer({ storage: multer.memoryStorage() });
router.get('/', authenticate, getProcedures);
router.get('/export', authenticate, exportProcedures);
router.post('/import', authenticate, upload.single('file'), importProcedures);
router.post('/', authenticate, createProcedure);
router.put('/:id', authenticate, updateProcedure);
router.delete('/:id', authenticate, deleteProcedure);
export default router;
