import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware';
import { getProductionlines, createProductionline, updateProductionline, deleteProductionline, exportProductionlines, importProductionlines } from '../controllers/productionline.controller';
const router = Router();
router.get('/', authenticate, getProductionlines);
router.post('/', authenticate, createProductionline);
router.put('/:id', authenticate, updateProductionline);
router.delete('/:id', authenticate, deleteProductionline);
router.get('/export', authenticate, exportProductionlines);
router.post('/import', authenticate, importProductionlines);
export default router;
