import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware';
import multer from 'multer';
import { getRoutings, createRouting, updateRouting, deleteRouting, exportRoutings, importRoutings } from '../controllers/routing.controller';
const router = Router();
const upload = multer({ storage: multer.memoryStorage() });
router.get('/', authenticate, getRoutings);
router.get('/export', authenticate, exportRoutings);
router.post('/import', authenticate, upload.single('file'), importRoutings);
router.post('/', authenticate, createRouting);
router.put('/:id', authenticate, updateRouting);
router.delete('/:id', authenticate, deleteRouting);
export default router;
