import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware';
import { getWorkshops, createWorkshop, updateWorkshop, deleteWorkshop, exportWorkshops, importWorkshops } from '../controllers/workshop.controller';
const router = Router();
router.get('/', authenticate, getWorkshops);
router.post('/', authenticate, createWorkshop);
router.put('/:id', authenticate, updateWorkshop);
router.delete('/:id', authenticate, deleteWorkshop);
router.get('/export', authenticate, exportWorkshops);
router.post('/import', authenticate, importWorkshops);
export default router;
