import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware';
import multer from 'multer';
import { getWorkCenters, createWorkCenter, updateWorkCenter, deleteWorkCenter, exportWorkCenters, importWorkCenters } from '../controllers/workCenter.controller';
const router = Router();
const upload = multer({ storage: multer.memoryStorage() });
router.get('/', authenticate, getWorkCenters);
router.get('/export', authenticate, exportWorkCenters);
router.post('/import', authenticate, upload.single('file'), importWorkCenters);
router.post('/', authenticate, createWorkCenter);
router.put('/:id', authenticate, updateWorkCenter);
router.delete('/:id', authenticate, deleteWorkCenter);
export default router;
