import { Router } from 'express';
import { validateCreateProcedure, validateUpdateProcedure } from '../../../validators/master-data.validator';
import { authenticate } from '../../../middleware/auth.middleware';
import multer from 'multer';
import { getProcedures, createProcedure, updateProcedure, deleteProcedure, exportProcedures, importProcedures, approveProcedure, withdrawProcedure } from './procedure.controller';
const router = Router();
const upload = multer({ storage: multer.memoryStorage() });
router.get('/', authenticate, getProcedures);
router.get('/export', authenticate, exportProcedures);
router.post('/import', authenticate, upload.single('file'), importProcedures);
router.post('/', authenticate, validateCreateProcedure, createProcedure);
router.put('/:id', authenticate, validateUpdateProcedure, updateProcedure);
router.delete('/:id', authenticate, deleteProcedure);
router.put('/:id/approve', authenticate, approveProcedure);
router.put('/:id/withdraw', authenticate, withdrawProcedure);
export default router;
